name: .NET

on:
  release:
    types: [ published ]

env:
    PROJECT_NAME: Juniperr.Blazor.BreadcrumbNavigation
    GITHUB_FEED: https://nuget.pkg.github.com/jnprr/
    GITHUB_USER: cschulzsuper
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    PACKAGE_VERSION: ${GITHUB_REF#refs/*/}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
          
    - uses: actions/checkout@v2
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore src/$PROJECT_NAME/$PROJECT_NAME.csproj
      
    - name: Pack
      run: dotnet pack -v normal -c Release --no-restore --include-symbols --include-source -p:PackageVersion=$PACKAGE_VERSION src/$PROJECT_NAME/$PROJECT_NAME.csproj
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: ./src/${{ env.PROJECT_NAME }}/bin/Release/*.nupkg

  prerelease:
    needs: build
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: nupkg
      - name: Push to GitHub Feed
        run: |
          for f in ./nupkg/*.nupkg
          do
            curl -vX PUT -u "$GITHUB_USER:$GITHUB_TOKEN" -F package=@$f $GITHUB_FEED
          done
