name: Deploy Sample

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
    PROJECT_NAME: Juniperr.Blazor.BreadcrumbNavigation
    PACKAGE_VERSION: ${{ git.closest.tag.name }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
          
    - uses: actions/checkout@v2
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore -p:Version=${PACKAGE_VERSION//v} src/$PROJECT_NAME/$PROJECT_NAME.csproj
      
    - name: Pack
      run: dotnet pack -v normal -c Release --no-restore --include-symbols --include-source -p:PackageVersion=${PACKAGE_VERSION//v} src/$PROJECT_NAME/$PROJECT_NAME.csproj

    - name: Publish Sample Site
      run: dotnet publish -c Release samples/BlazorWebAssembly/BlazorWebAssembly.csproj

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: samples/BlazorWebAssembly/bin/Release/net5.0/publish/wwwroot/index.html
        base_href: /${{ env.PROJECT_NAME }}/
    
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: sample # The branch the action should deploy to.
        FOLDER: samples/BlazorWebAssembly/bin/Release/net5.0/publish/wwwroot # The folder the action should deploy.
        SINGLE_COMMIT: true
